#ifndef PINLAYOUT
#define PINLAYOUT

#define BUTTONLINKSHOCH    D1
#define BUTTONRECHTSHOCH   D2
#define BUTTONLINKSRUNTER  D5
#define BUTTONRECHTSRUNTER D6

#define MOTORLINKSPOWER     D3
#define MOTORLINKSRICHTUNG  D4
#define MOTORRECHTSPOWER    D7
#define MOTORRECHTSRICHTUNG D8

//#define LED_BUILTIN 2

#endif
