#ifndef PINLAYOUT
#define PINLAYOUT

#define BUTTONLINKSHOCH    34
#define BUTTONRECHTSHOCH   35
#define BUTTONLINKSRUNTER  36
#define BUTTONRECHTSRUNTER 39

#define MOTORLINKSPOWER     GPIO_NUM_26
#define MOTORLINKSRICHTUNG  GPIO_NUM_25
#define MOTORRECHTSPOWER    GPIO_NUM_33
#define MOTORRECHTSRICHTUNG GPIO_NUM_32

#define LED_BUILTIN 2

#endif
