#ifndef PINLAYOUT
#define PINLAYOUT

#define BUTTONLINKSHOCH    GPIO_NUM_34
#define BUTTONRECHTSHOCH   GPIO_NUM_36
#define BUTTONLINKSRUNTER  GPIO_NUM_35
#define BUTTONRECHTSRUNTER GPIO_NUM_39

#define MOTORLINKSPOWER     GPIO_NUM_32
#define MOTORLINKSRICHTUNG  GPIO_NUM_33
#define MOTORRECHTSPOWER    GPIO_NUM_25
#define MOTORRECHTSRICHTUNG GPIO_NUM_26

#define LED_BUILTIN 2

#endif
